name: Build and Push to gh-pages

on:
  push:
    branches: [ "main" ]   # 当 main 分支有推送时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.30.3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v24.14.0
          cache: pnpm
      - name: Install dependency
        run: pnpm install --frozen-lockfile
      - name: Build docs
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run docs:build  # 确保生成 dist 目录

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist      # 指定构建产物目录
          publish_branch: gh-pages # 推送到 gh-pages 分支
          force_orphan: true       # 使 gh-pages 分支只包含最新的文件，没有历史记录（可选）
